name: create-map
on: push

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: stefanzweifel/git-auto-commit-action@v4
    - name: Run script file
      run: |
         chmod +x ./runme.sh
         ./runme.sh
      shell: bash
    - name: Commit report
      run: |
        git commit -m "<some commit message>"
        git push
