name: copy files to chrome folder
on: 
  push:
  schedule:
    # min hours day(month) month day(week)
    - cron: "0 0 * * *"
jobs:
  run_tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Run script file
      run: |
         chmod +x ./runme.sh
         ./runme.sh
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
