name: create-map
on: push

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
        check-latest: true
    - name: Run script file
      run: |
         git submodule sync
         git submodule update --init --recursive
         chmod +x ./runme.sh
         ./runme.sh
      shell: bash
